2021-01-08 16:20:52,530 INFO 24448 [egg-sequelize](2ms) Executed (default): SELECT 1+1 AS result
2021-01-08 16:22:05,671 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'user_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at Function.findOne (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1917:12)
    at UserService.login (E:\Instagram-master\service\app\service\user.ts:65:27)
    at UserController.loginIn (E:\Instagram-master\service\app\controller\login.ts:28:23)
    at E:\Instagram-master\service\app\middleware\authorization.ts:7:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"}
sql: "SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:22:27,494 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'user_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at Function.findOne (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1917:12)
    at UserService.login (E:\Instagram-master\service\app\service\user.ts:65:27)
    at UserController.loginIn (E:\Instagram-master\service\app\controller\login.ts:28:23)
    at E:\Instagram-master\service\app\middleware\authorization.ts:7:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"}
sql: "SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:23:01,941 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'user_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at Function.findOne (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1917:12)
    at UserService.login (E:\Instagram-master\service\app\service\user.ts:65:27)
    at UserController.loginIn (E:\Instagram-master\service\app\controller\login.ts:28:23)
    at E:\Instagram-master\service\app\middleware\authorization.ts:7:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'codingzx@gmail.com' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'codingzx@gmail.com' LIMIT 1;"}
sql: "SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'codingzx@gmail.com' LIMIT 1;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:23:17,533 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'user_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at Function.findOne (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1917:12)
    at UserService.login (E:\Instagram-master\service\app\service\user.ts:65:27)
    at UserController.loginIn (E:\Instagram-master\service\app\controller\login.ts:28:23)
    at E:\Instagram-master\service\app\middleware\authorization.ts:7:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'shawzhou' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'shawzhou' LIMIT 1;"}
sql: "SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'shawzhou' LIMIT 1;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:23:51,051 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'user_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at Function.findOne (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1917:12)
    at UserService.login (E:\Instagram-master\service\app\service\user.ts:65:27)
    at UserController.loginIn (E:\Instagram-master\service\app\controller\login.ts:28:23)
    at E:\Instagram-master\service\app\middleware\authorization.ts:7:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'shawzhou' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'shawzhou' LIMIT 1;"}
sql: "SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'shawzhou' LIMIT 1;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:23:57,307 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'user_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at Function.findOne (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1917:12)
    at UserService.login (E:\Instagram-master\service\app\service\user.ts:65:27)
    at UserController.loginIn (E:\Instagram-master\service\app\controller\login.ts:28:23)
    at E:\Instagram-master\service\app\middleware\authorization.ts:7:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'shawzhou' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'shawzhou' LIMIT 1;"}
sql: "SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = 'shawzhou' LIMIT 1;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:27:43,940 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'avatar_url' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at Function.findOne (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1917:12)
    at UserService.login (E:\Instagram-master\service\app\service\user.ts:65:27)
    at UserController.loginIn (E:\Instagram-master\service\app\controller\login.ts:28:23)
    at E:\Instagram-master\service\app\middleware\authorization.ts:7:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'avatar_url' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'avatar_url' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"}
sql: "SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:27:52,774 ERROR 24448 [-/127.0.0.1/-/1ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'avatar_url' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at Function.findOne (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1917:12)
    at UserService.login (E:\Instagram-master\service\app\service\user.ts:65:27)
    at UserController.loginIn (E:\Instagram-master\service\app\controller\login.ts:28:23)
    at E:\Instagram-master\service\app\middleware\authorization.ts:7:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'avatar_url' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'avatar_url' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"}
sql: "SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:29:27,645 INFO 24448 [egg-sequelize](6ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`email` = '466150516@qq.com' LIMIT 1;
2021-01-08 16:29:27,694 INFO 24448 [egg-sequelize](3ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd' LIMIT 1;
2021-01-08 16:29:28,261 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'user_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at UserService.getUserList (E:\Instagram-master\service\app\service\user.ts:150:27)
    at FriendController.notFollowList (E:\Instagram-master\service\app\controller\friend.ts:31:26)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
    at E:\Instagram-master\service\app\middleware\error_handler.ts:17:9
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"}
sql: "SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:29:28,288 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'user_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at followService.findFollow (E:\Instagram-master\service\app\service\follow.ts:37:16)
    at TopicController.friendsTopicList (E:\Instagram-master\service\app\controller\topic.ts:73:25)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
    at E:\Instagram-master\service\app\middleware\error_handler.ts:17:9
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'user_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"}
sql: "SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:31:25,194 ERROR 24448 [-/127.0.0.1/-/1ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'follow.followed_id' in 'where clause'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at UserService.getUserList (E:\Instagram-master\service\app\service\user.ts:150:27)
    at FriendController.notFollowList (E:\Instagram-master\service\app\controller\friend.ts:31:26)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
    at E:\Instagram-master\service\app\middleware\error_handler.ts:17:9
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'follow.followed_id' in 'where clause'","sql":"SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'follow.followed_id' in 'where clause'","sql":"SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"}
sql: "SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:31:25,202 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'followed_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at followService.findFollow (E:\Instagram-master\service\app\service\follow.ts:37:16)
    at TopicController.friendsTopicList (E:\Instagram-master\service\app\controller\topic.ts:73:25)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
    at E:\Instagram-master\service\app\middleware\error_handler.ts:17:9
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'followed_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'followed_id' in 'field list'","sql":"SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"}
sql: "SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:31:25,204 INFO 24448 [egg-sequelize](18ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd' LIMIT 1;
2021-01-08 16:32:30,366 INFO 24448 [egg-sequelize](3ms) Executed (default): SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:32:30,374 INFO 24448 [egg-sequelize](10ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:32:30,381 INFO 24448 [egg-sequelize](17ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd' LIMIT 1;
2021-01-08 16:32:30,385 INFO 24448 [egg-sequelize](14ms) Executed (default): SELECT `user_id` AS `userId`, `username`, `email`, `avatar_url` AS `avatarUrl`, `abstract` FROM `users` AS `users` WHERE (`users`.`user_id` != 'cbd6eb6093e74c7290aad936e8a9a2cd' AND `users`.`user_id` NOT IN ('e51c2d2e4366433fb35f017c69468149'));
2021-01-08 16:32:30,398 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'topic_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at TopicService.queryTopicList (E:\Instagram-master\service\app\service\topic.ts:48:16)
    at TopicController.friendsTopicList (E:\Instagram-master\service\app\controller\topic.ts:87:22)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
    at E:\Instagram-master\service\app\middleware\error_handler.ts:17:9
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'topic_id' in 'field list'","sql":"SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'topic_id' in 'field list'","sql":"SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"}
sql: "SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:35:18,715 INFO 24448 [egg-sequelize](2ms) Executed (default): SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:35:18,720 INFO 24448 [egg-sequelize](6ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:35:18,724 INFO 24448 [egg-sequelize](9ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd' LIMIT 1;
2021-01-08 16:35:18,727 INFO 24448 [egg-sequelize](9ms) Executed (default): SELECT `user_id` AS `userId`, `username`, `email`, `avatar_url` AS `avatarUrl`, `abstract` FROM `users` AS `users` WHERE (`users`.`user_id` != 'cbd6eb6093e74c7290aad936e8a9a2cd' AND `users`.`user_id` NOT IN ('e51c2d2e4366433fb35f017c69468149'));
2021-01-08 16:35:18,737 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'topic_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at TopicService.queryTopicList (E:\Instagram-master\service\app\service\topic.ts:48:16)
    at TopicController.friendsTopicList (E:\Instagram-master\service\app\controller\topic.ts:87:22)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
    at E:\Instagram-master\service\app\middleware\error_handler.ts:17:9
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'topic_id' in 'field list'","sql":"SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'topic_id' in 'field list'","sql":"SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"}
sql: "SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:37:50,288 INFO 24448 [egg-sequelize](2ms) Executed (default): SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:37:50,292 INFO 24448 [egg-sequelize](3ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:37:50,298 INFO 24448 [egg-sequelize](4ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd' LIMIT 1;
2021-01-08 16:37:50,309 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'topic_title' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at TopicService.queryTopicList (E:\Instagram-master\service\app\service\topic.ts:48:16)
    at TopicController.friendsTopicList (E:\Instagram-master\service\app\controller\topic.ts:87:22)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
    at E:\Instagram-master\service\app\middleware\error_handler.ts:17:9
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'topic_title' in 'field list'","sql":"SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'topic_title' in 'field list'","sql":"SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"}
sql: "SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:37:50,312 INFO 24448 [egg-sequelize](16ms) Executed (default): SELECT `user_id` AS `userId`, `username`, `email`, `avatar_url` AS `avatarUrl`, `abstract` FROM `users` AS `users` WHERE (`users`.`user_id` != 'cbd6eb6093e74c7290aad936e8a9a2cd' AND `users`.`user_id` NOT IN ('e51c2d2e4366433fb35f017c69468149'));
2021-01-08 16:38:36,809 INFO 24448 [egg-sequelize](2ms) Executed (default): SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:38:36,814 INFO 24448 [egg-sequelize](3ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd' LIMIT 1;
2021-01-08 16:38:36,818 INFO 24448 [egg-sequelize](10ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:38:36,824 INFO 24448 [egg-sequelize](11ms) Executed (default): SELECT `user_id` AS `userId`, `username`, `email`, `avatar_url` AS `avatarUrl`, `abstract` FROM `users` AS `users` WHERE (`users`.`user_id` != 'cbd6eb6093e74c7290aad936e8a9a2cd' AND `users`.`user_id` NOT IN ('e51c2d2e4366433fb35f017c69468149'));
2021-01-08 16:38:36,835 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'topic_img' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at TopicService.queryTopicList (E:\Instagram-master\service\app\service\topic.ts:48:16)
    at TopicController.friendsTopicList (E:\Instagram-master\service\app\controller\topic.ts:87:22)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
    at E:\Instagram-master\service\app\middleware\error_handler.ts:17:9
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'topic_img' in 'field list'","sql":"SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'topic_img' in 'field list'","sql":"SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"}
sql: "SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:39:26,943 INFO 24448 [egg-sequelize](3ms) Executed (default): SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:39:26,947 INFO 24448 [egg-sequelize](4ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:39:26,951 INFO 24448 [egg-sequelize](9ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd' LIMIT 1;
2021-01-08 16:39:26,955 INFO 24448 [egg-sequelize](9ms) Executed (default): SELECT `user_id` AS `userId`, `username`, `email`, `avatar_url` AS `avatarUrl`, `abstract` FROM `users` AS `users` WHERE (`users`.`user_id` != 'cbd6eb6093e74c7290aad936e8a9a2cd' AND `users`.`user_id` NOT IN ('e51c2d2e4366433fb35f017c69468149'));
2021-01-08 16:39:26,961 INFO 24448 [egg-sequelize](12ms) Executed (default): SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;
2021-01-08 16:39:26,967 INFO 24448 [egg-sequelize](1ms) Executed (default): SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`topic_id` = 4;
2021-01-08 16:39:26,971 INFO 24448 [egg-sequelize](1ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'e51c2d2e4366433fb35f017c69468149' LIMIT 1;
2021-01-08 16:39:26,984 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'discuss_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at TopicService.queryDiscuss (E:\Instagram-master\service\app\service\topic.ts:181:16)
    at TopicService.topicDetailHanderl (E:\Instagram-master\service\app\service\topic.ts:72:23)
    at TopicController.friendsTopicList (E:\Instagram-master\service\app\controller\topic.ts:96:24)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'discuss_id' in 'field list'","sql":"SELECT `discuss_id` AS `discussId`, `topic_id` AS `topicId`, `user_id` AS `userId`, `reply_name` AS `replyName`, `reply_content` AS `replyContent`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `discuss` AS `discuss` WHERE `discuss`.`topic_id` = 4;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'discuss_id' in 'field list'","sql":"SELECT `discuss_id` AS `discussId`, `topic_id` AS `topicId`, `user_id` AS `userId`, `reply_name` AS `replyName`, `reply_content` AS `replyContent`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `discuss` AS `discuss` WHERE `discuss`.`topic_id` = 4;"}
sql: "SELECT `discuss_id` AS `discussId`, `topic_id` AS `topicId`, `user_id` AS `userId`, `reply_name` AS `replyName`, `reply_content` AS `replyContent`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `discuss` AS `discuss` WHERE `discuss`.`topic_id` = 4;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

2021-01-08 16:49:36,003 WARN 24448 A client (::ffff:192.168.0.16:58611) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2021-01-08 16:49:36,611 WARN 24448 A client (::ffff:192.168.0.16:58617) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2021-01-08 16:51:28,583 INFO 24448 [egg-sequelize](2ms) Executed (default): SELECT `user_id` AS `userId` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:51:28,588 INFO 24448 [egg-sequelize](7ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `followed_id` AS `followedId`, `status`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `follow` AS `follow` WHERE `follow`.`status` = 1 AND `follow`.`followed_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd';
2021-01-08 16:51:28,591 INFO 24448 [egg-sequelize](9ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'cbd6eb6093e74c7290aad936e8a9a2cd' LIMIT 1;
2021-01-08 16:51:28,594 INFO 24448 [egg-sequelize](9ms) Executed (default): SELECT `user_id` AS `userId`, `username`, `email`, `avatar_url` AS `avatarUrl`, `abstract` FROM `users` AS `users` WHERE (`users`.`user_id` != 'cbd6eb6093e74c7290aad936e8a9a2cd' AND `users`.`user_id` NOT IN ('e51c2d2e4366433fb35f017c69468149'));
2021-01-08 16:51:28,598 INFO 24448 [egg-sequelize](8ms) Executed (default): SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`user_id` IN ('e51c2d2e4366433fb35f017c69468149', 'cbd6eb6093e74c7290aad936e8a9a2cd') ORDER BY `topic`.`created_at` DESC;
2021-01-08 16:51:28,603 INFO 24448 [egg-sequelize](2ms) Executed (default): SELECT `topic_id` AS `topicId`, `user_id` AS `userId`, `topic_title` AS `topicTitle`, `topic_img` AS `topicImg`, `address`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `topic` AS `topic` WHERE `topic`.`topic_id` = 4;
2021-01-08 16:51:28,607 INFO 24448 [egg-sequelize](2ms) Executed (default): SELECT `id`, `user_id` AS `userId`, `username`, `email`, `password`, `avatar_url` AS `avatarUrl`, `mobile`, `prefix`, `abstract`, `sex`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `users` AS `users` WHERE `users`.`user_id` = 'e51c2d2e4366433fb35f017c69468149' LIMIT 1;
2021-01-08 16:51:28,618 ERROR 24448 [-/127.0.0.1/-/0ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'discuss_id' in 'field list'
    at Query.formatError (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
    at Query.run (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\mysql\query.js:54:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at E:\Instagram-master\service\node_modules\sequelize\lib\sequelize.js:619:16
    at MySQLQueryInterface.select (E:\Instagram-master\service\node_modules\sequelize\lib\dialects\abstract\query-interface.js:938:12)
    at Function.findAll (E:\Instagram-master\service\node_modules\sequelize\lib\model.js:1753:21)
    at TopicService.queryDiscuss (E:\Instagram-master\service\app\service\topic.ts:181:16)
    at TopicService.topicDetailHanderl (E:\Instagram-master\service\app\service\topic.ts:72:23)
    at TopicController.friendsTopicList (E:\Instagram-master\service\app\controller\topic.ts:96:24)
    at E:\Instagram-master\service\app\middleware\authorization.ts:20:7
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'discuss_id' in 'field list'","sql":"SELECT `discuss_id` AS `discussId`, `topic_id` AS `topicId`, `user_id` AS `userId`, `reply_name` AS `replyName`, `reply_content` AS `replyContent`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `discuss` AS `discuss` WHERE `discuss`.`topic_id` = 4;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'discuss_id' in 'field list'","sql":"SELECT `discuss_id` AS `discussId`, `topic_id` AS `topicId`, `user_id` AS `userId`, `reply_name` AS `replyName`, `reply_content` AS `replyContent`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `discuss` AS `discuss` WHERE `discuss`.`topic_id` = 4;"}
sql: "SELECT `discuss_id` AS `discussId`, `topic_id` AS `topicId`, `user_id` AS `userId`, `reply_name` AS `replyName`, `reply_content` AS `replyContent`, `created_at`, `updated_at`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `discuss` AS `discuss` WHERE `discuss`.`topic_id` = 4;"
parameters: undefined
pid: 24448
hostname: PC-20200908FRFL

